[package]
name = "padpad-software"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { path = "vendor/egui/crates/eframe/", features = ["default"] }
env_logger = { version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
] }
