name: Release Build
permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            package_os: linux
            archive_ext: tar.gz

          - os: windows-latest
            package_os: windows
            archive_ext: zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglib2.0-dev \
            libgtk-3-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libxcursor-dev \
            libudev-dev \
            libxdo-dev \
            pkg-config

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build binaries
        run: |
          cargo build --release
          cargo build --release --bin dashboard

      - name: Prepare Linux artifacts
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv target/release/padpad-software padpad
          mv target/release/dashboard dashboard
          tar czf padpad-${{ matrix.package_os }}-${{ github.ref_name }}.${{ matrix.archive_ext }} padpad dashboard LICENSE README.md

      - name: Prepare Windows artifacts
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Move-Item target/release/padpad-software.exe PadPad.exe
          Move-Item target/release/dashboard.exe Dashboard.exe
          Compress-Archive -Path PadPad.exe, Dashboard.exe, LICENSE, README.md -DestinationPath padpad-${{ matrix.package_os }}-${{ github.ref_name }}.zip

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            padpad-${{ matrix.package_os }}-${{ github.ref_name }}.${{ matrix.archive_ext }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
